create table "public"."habits" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "user_id" uuid not null,
    "created_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone not null
);


create table "public"."trackers" (
    "id" bigint generated by default as identity not null,
    "date" date not null,
    "habit_id" uuid not null,
    "completed" boolean not null,
    "created_at" timestamp with time zone not null,
    "updated_at" timestamp with time zone not null
);


alter table "public"."memos" disable row level security;

CREATE UNIQUE INDEX habits_pkey ON public.habits USING btree (id);

CREATE UNIQUE INDEX trackers_pkey ON public.trackers USING btree (id);

alter table "public"."habits" add constraint "habits_pkey" PRIMARY KEY using index "habits_pkey";

alter table "public"."trackers" add constraint "trackers_pkey" PRIMARY KEY using index "trackers_pkey";

alter table "public"."habits" add constraint "habits_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."habits" validate constraint "habits_user_id_fkey";

alter table "public"."trackers" add constraint "trackers_habit_id_fkey" FOREIGN KEY (habit_id) REFERENCES habits(id) not valid;

alter table "public"."trackers" validate constraint "trackers_habit_id_fkey";

grant delete on table "public"."habits" to "anon";

grant insert on table "public"."habits" to "anon";

grant references on table "public"."habits" to "anon";

grant select on table "public"."habits" to "anon";

grant trigger on table "public"."habits" to "anon";

grant truncate on table "public"."habits" to "anon";

grant update on table "public"."habits" to "anon";

grant delete on table "public"."habits" to "authenticated";

grant insert on table "public"."habits" to "authenticated";

grant references on table "public"."habits" to "authenticated";

grant select on table "public"."habits" to "authenticated";

grant trigger on table "public"."habits" to "authenticated";

grant truncate on table "public"."habits" to "authenticated";

grant update on table "public"."habits" to "authenticated";

grant delete on table "public"."habits" to "service_role";

grant insert on table "public"."habits" to "service_role";

grant references on table "public"."habits" to "service_role";

grant select on table "public"."habits" to "service_role";

grant trigger on table "public"."habits" to "service_role";

grant truncate on table "public"."habits" to "service_role";

grant update on table "public"."habits" to "service_role";

grant delete on table "public"."trackers" to "anon";

grant insert on table "public"."trackers" to "anon";

grant references on table "public"."trackers" to "anon";

grant select on table "public"."trackers" to "anon";

grant trigger on table "public"."trackers" to "anon";

grant truncate on table "public"."trackers" to "anon";

grant update on table "public"."trackers" to "anon";

grant delete on table "public"."trackers" to "authenticated";

grant insert on table "public"."trackers" to "authenticated";

grant references on table "public"."trackers" to "authenticated";

grant select on table "public"."trackers" to "authenticated";

grant trigger on table "public"."trackers" to "authenticated";

grant truncate on table "public"."trackers" to "authenticated";

grant update on table "public"."trackers" to "authenticated";

grant delete on table "public"."trackers" to "service_role";

grant insert on table "public"."trackers" to "service_role";

grant references on table "public"."trackers" to "service_role";

grant select on table "public"."trackers" to "service_role";

grant trigger on table "public"."trackers" to "service_role";

grant truncate on table "public"."trackers" to "service_role";

grant update on table "public"."trackers" to "service_role";


